# This is a basic workflow to help you get started with Actions

name: spydy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: termux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:virus
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
      run:echo start www.google.com
      start www.google.com
      start www.google.com
      goto:run 

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |you have been hacked lol
        echo Add other actions to build,
        echo test, and deploy your project.
